FROM alpine:3.6
#RUN echo http://172.17.0.4:3143/alpine/v3.6/main > /etc/apk/repositories
#RUN echo http://172.17.0.4:3143/alpine/v3.6/community >> /etc/apk/repositories
RUN apk update
RUN apk add rsync
RUN echo "[alpine]" >> /etc/rsyncd.conf
RUN echo "      path = /var/www/localhost/htdocs/alpine" >> /etc/rsyncd.conf
RUN echo "      comment = My Alpine Linux Mirror" >> /etc/rsyncd.conf
RUN rsync --help
CMD /usr/bin/rsync --daemon --config /etc/rsyncd.conf --log-file=-
